# Helper ClusterRole for cluster administrators to grant edit access to EphemeralDeployment resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sandglass
    app.kubernetes.io/managed-by: kustomize
  name: ephemeraldeployment-editor-role
rules:
- apiGroups:
  - sandglass.io
  resources:
  - ephemeraldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sandglass.io
  resources:
  - ephemeraldeployments/status
  verbs:
  - get
