name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  test-e2e:
    permissions:
      contents: read
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Run E2E Tests
        run: mise run test-e2e
